


version: '3.8'
services:
  flowable-ui:
    image: flowable/flowable-ui:6.8.0
    container_name: flowable-ui6
    restart: always
#    volumes:
#      - ./mysql-connector-java-8.0.19.jar:/app/WEB-INF/lib/mysql-connector-java-8.0.19.jar
    environment:
      - TZ=Asia/Shanghai
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver # mysql8驱动
      - spring.datasource.url=jdbc:mysql://mysql8:3306/flowable?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false&nullCatalogMeansCurrent=true
      - spring.datasource.username=root        # 数据库账号
      - spring.datasource.password=123456        # 数据库密码
      - flowable.async-executor-activate=false # 关闭定时任务JOB
      - flowable.database-schema-update=true   # 当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本
    ports:
      - "14001:8080"
    privileged: true
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "500m"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true


