version: '3.8'
services:
  my-nacos:
    # 对应 springboot 2.6.13
    #  Spring Cloud 2021.0.5
    # Spring Cloud Alibaba 2021.0.5.0*
    image: nacos/nacos-server:v2.2.0
    container_name: my-nacos
    # restart: always
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=hadoop102
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
    volumes:
      - /etc/hosts:/etc/hosts # 挂载hosts
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      mynetwork:
      #ipv4_address: 172.19.0.12
#    depends_on:
#      - mysql8

#  mysql8:
#    image: mysql:8.0.33
#    container_name: mysql8
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      TZ: Asia/Shanghai
#    ports:
#      - "3306:3306"
#    volumes:
#      - /opt/mydata/mysql8/data:/var/lib/mysql
#    networks:
#      mynetwork:
networks:
  mynetwork:
    external: true
