version: '3'
services:
  nacos:
    # 对应 springboot 2.6.13
    #  Spring Cloud 2021.0.5
    # Spring Cloud Alibaba 2021.0.5.0*
    image: nacos/nacos-server:v2.2.0
    container_name: nacos
    #    restart: always
    # restart: always
    environment:
      - MODE=standalone # 或者 standalone 如果是单机模式
      - SPRING_DATASOURCE_PLATFORM=mysql
#      - MYSQL_SERVICE_HOST=mysql8 # 替换为你的MySQL主机地址
      - MYSQL_SERVICE_HOST=hadoop102 # 替换为你的MySQL主机地址
      - MYSQL_SERVICE_PORT=3306 # MySQL端口，默认是3306
      - MYSQL_SERVICE_DB_NAME=nacos # 替换为你想要使用的数据库名称
      - MYSQL_SERVICE_USER=root # 替换为你的MySQL用户名
      - MYSQL_SERVICE_PASSWORD=123456 # 替换为你的MySQL密码
      - JAVA_OPTS=-Xms128m -Xmx128m -Xmn128m
    volumes:
      - /etc/hosts:/etc/hosts # 挂载hosts
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      mynetwork:
      #ipv4_address: 172.19.0.12

networks:
  mynetwork:
    external: true
