global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysqld-exporter:9104

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter-135:9121',  'redis-exporter-11:9121']
        labels:
          instance: redis-production  # 设置Redis实例标识
