version: '3.8'

services:
  streampark:
    image: apache/streampark:2.1.4
    ports:
      - "10000:10000"
      - "10030:10030"
    environment:
      - TZ=Asia/Shanghai
      - DATASOURCE_DIALECT=h2 # h2, mysql, pgsql
#     If use mysql or pgsql, please set the following parameters
#     - DATASOURCE_URL=jdbc:mysql://localhost:3306/streampark?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#     - DATASOURCE_URL=jdbc:postgresql://localhost:5432/streampark?stringtype=unspecified
#     - DATASOURCE_USERNAME=root
#     - DATASOURCE_PASSWORD=streampark
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hosts:/etc/hosts:ro
      - ~/.kube:/root/.kube:ro
    privileged: true
    restart: always
    networks:
      - streampark
    healthcheck:
      test: [ "CMD", "curl", "http://streampark:10000" ]
      interval: 5s
      timeout: 5s
      retries: 120

networks:
  streampark:
    driver: bridge