#version: "3.6"
#services:
#  kafka1:
#    container_name: kafka1
#    image: 'bitnami/kafka:3.5.2'
#    user: root
#    ports:
#      - '19092:9092'
#      - '19093:9093'
#    environment:
#      # 允许使用Kraft
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      # 定义kafka服务端socket监听端口（Docker内部的ip地址和端口）
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      # 定义安全协议
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.26.80.1:19092
##      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.101.132:19092
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_NODE_ID=1
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
#      - KAFKA_KRAFT_CLUSTER_ID=iZWRiSqjZAlYwlKEqHFQWI
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      # 设置broker最大内存，和初始内存
#      - KAFKA_HEAP_OPTS=-Xmx256M -Xms256M
##    volumes:
##      - ./broker01:/bitnami/kafka:rw
##    network_mode: host
#    # networks:
#    #   netkafka:
#    #     ipv4_address: 172.23.0.11

version: "3.6"
services:
  kafka:
    container_name: kafka3
    image: 'bitnami/kafka:3.8.0'
    restart: unless-stopped
    ports:
      - "9092:9092"
    extra_hosts:
      - "hadoop102:192.168.10.102"
      - "hadoop103:192.168.10.103"
      - "hadoop104:192.168.10.104"
    volumes:
      - "./data:/bitnami/data"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      # 外部访问url,根据实际情况修改,不能使用虚拟hosts
      #===================================重点===================================
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://hadoop102:9092
      #=========================================================================
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
