

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://192.168.101.143:9092" #本机ip,不然无法链接
    depends_on:
      - zookeeper

#volumes:
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local
